###Request para obtener los usuarios
GET http://3.129.71.50:8080/ingsoft-0.0.1-SNAPSHOT/zonas/allZonas
Accept: application/json

###

GET http://3.129.71.50:8080/ingsoft-0.0.1-SNAPSHOT/zonas/zonaById?zonaId=2
Accept: application/json
