spring:
  application:
    name: ingsoft
  datasource:
    name: demo_mysql_db
    platform: mysql
    url: jdbc:mysql://b5b0a0fe438319:5a79e427@us-cdbr-east-04.cleardb.com/heroku_f9435daf7d460d2?reconnect=true
    username: b5b0a0fe438319
    password: 5a79e427
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000

logging:
  level:
    com:
      spring:
        ibatis:
          UserMapper=DEBUG:

mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/dao/*Dao.xml

server:
  port: 8083


